'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Shield, ChevronRight, Smartphone, AlertTriangle, UserCheck, ShieldCheck } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useLang } from '../lib/lang';

export default function Home() {
  const { t } = useLang();

  const fadeInUp = {
    hidden: { opacity: 0, y: 30 },
    show: { opacity: 1, y: 0, transition: { duration: 0.6 } }
  };

  return (
    <>
      <Navbar />
      <main style={{ paddingTop: 64, flex: 1 }}>
        
        {/* HERO SECTION - Redesigned to feel less generic */}
        <section className="hero-gradient" style={{ padding: '80px 24px', overflow: 'hidden', minHeight: '80vh', display: 'flex', alignItems: 'center' }}>
          <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 60, alignItems: 'center' }}>
            
            <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: 0.1 } } }}>
              <motion.div variants={fadeInUp} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '8px 16px', background: 'var(--surface-glass)', borderRadius: 30, border: '1px solid var(--border)', marginBottom: 24 }}>
                <div style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--safe)' }} className="pulse-glow" />
                <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>100% Buatan Indonesia 🇮🇩</span>
              </motion.div>

              <motion.h1 variants={fadeInUp} style={{ fontSize: 'clamp(36px, 5vw, 60px)', fontWeight: 900, lineHeight: 1.1, marginBottom: 20, letterSpacing: '-1px' }}>
                Jangan Jadi Korban <br/>
                <span className="gradient-text">Penipuan Digital!</span>
              </motion.h1>

              <motion.p variants={fadeInUp} style={{ fontSize: 18, color: 'var(--text-secondary)', marginBottom: 40, lineHeight: 1.6, maxWidth: 480 }}>
                Lindungi diri Anda dan keluarga dari Pinjol Ilegal, link Phishing di WhatsApp, penipuan toko online, dan Lowongan Kerja palsu dengan asisten keamanan AI kami.
              </motion.p>

              <motion.div variants={fadeInUp} style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                <Link href="/dashboard" style={{ textDecoration: 'none' }}>
                  <button className="btn-primary" style={{ padding: '16px 32px', fontSize: 16, borderRadius: 30 }}>
                    Mulai Cek Sekarang <ChevronRight size={18} />
                  </button>
                </Link>
              </motion.div>
              
              <motion.div variants={fadeInUp} style={{ marginTop: 32, display: 'flex', alignItems: 'center', gap: 12, color: 'var(--text-muted)', fontSize: 13 }}>
                <ShieldCheck size={20} color="var(--safe)" /> Terpercaya oleh Komunitas Digital Indonesia
              </motion.div>
            </motion.div>

            {/* Hero Illustration Generated by AI */}
            <motion.div 
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 1, type: 'spring' }}
              style={{ position: 'relative' }}
              className="float"
            >
              {/* Fallback styling just in case image doesn't load instantly */}
              <div style={{ position: 'absolute', inset: 40, background: 'var(--primary-glow)', borderRadius: '50%', filter: 'blur(60px)', zIndex: -1 }} />
              <img src="/hero.png" alt="Trustify Digital Shield Protection" style={{ width: '100%', height: 'auto', dropShadow: 'var(--shadow-lg)' }} />
            </motion.div>

          </div>
        </section>

        {/* WHY TRUSTIFY - Localized Context */}
        <section style={{ padding: '100px 24px', background: 'var(--surface)' }}>
          <div style={{ maxWidth: 1200, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 64 }}>
              <h2 style={{ fontSize: 32, fontWeight: 800, marginBottom: 12 }}>Masalah Nyata di Sekitar Kita</h2>
              <p style={{ color: 'var(--text-secondary)', maxWidth: 600, margin: '0 auto' }}>
                Setiap hari, ribuan orang tertipu jutaan rupiah karena kurangnya alat pengecekan yang mudah dan cepat.
              </p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
              {[
                { title: 'Undangan APK Palsu', desc: 'Sering mendapat pesan WhatsApp berisi file APK berkedok undangan nikah atau kurir paket? Jangan di-install!', icon: <Smartphone size={28} /> },
                { title: 'Jebakan Pinjol Ilegal', desc: 'Bunga mencekik dan teror debt collector dari aplikasi pinjaman yang tidak terdaftar resmi di OJK.', icon: <AlertTriangle size={28} /> },
                { title: 'Lowongan Bodong', desc: 'Disuruh transfer uang duluan untuk "biaya admin" dengan iming-iming gaji puluhan juta?', icon: <UserCheck size={28} /> },
              ].map((item, i) => (
                <motion.div key={i} initial="hidden" whileInView="show" viewport={{ once: true, margin: '-50px' }} variants={fadeInUp}
                  style={{ padding: 32, borderRadius: 24, background: 'var(--surface-2)', border: '1px solid var(--border)', position: 'relative', overflow: 'hidden' }}
                >
                  <div style={{ position: 'absolute', top: -20, right: -20, opacity: 0.05, transform: 'scale(3)' }}>{item.icon}</div>
                  <div style={{ width: 56, height: 56, borderRadius: 16, background: 'var(--danger-bg)', color: 'var(--danger)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 20 }}>
                    {item.icon}
                  </div>
                  <h3 style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>{item.title}</h3>
                  <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>{item.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* HOW IT WORKS / FEATURES */}
        <section id="features" style={{ padding: '100px 24px', background: 'var(--surface-2)' }}>
          <div style={{ maxWidth: 1200, margin: '0 auto' }}>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 40, alignItems: 'center' }}>
              
              <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeInUp}>
                <h2 style={{ fontSize: 36, fontWeight: 800, marginBottom: 24 }}>Satu Aplikasi, <br/><span className="gradient-text">Proteksi Penuh.</span></h2>
                <p style={{ color: 'var(--text-secondary)', fontSize: 18, marginBottom: 32, lineHeight: 1.6 }}>
                  Trustify menggunakan AI untuk menganalisa bahasa yang memanipulasi, mengecek *database* penipu, dan memperingatkan Anda sebelum Anda menekan tombol "Transfer" atau "Kirim".
                </p>
                <Link href="/dashboard" style={{ textDecoration: 'none' }}>
                  <button className="btn-secondary" style={{ padding: '12px 24px', borderRadius: 20 }}>
                    Jelajahi 10+ Fitur Keamanan <ChevronRight size={18} />
                  </button>
                </Link>
              </motion.div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                {[
                  { name: 'ScamShield', emoji: '🛡️', color: 'var(--primary)', desc: 'Cek No. Rekening & Tautan' },
                  { name: 'WiFiSecure', emoji: '📶', color: 'var(--safe)', desc: 'Cek Keamanan Jaringan' },
                  { name: 'HoaxLens', emoji: '🔍', color: 'var(--warning)', desc: 'Cek Fakta Berita WA' },
                  { name: 'PinjolCheck', emoji: '💰', color: 'var(--danger)', desc: 'Hindari Rentenir Digital' },
                ].map((f, i) => (
                  <motion.div key={i} initial={{ opacity: 0, scale: 0.9 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                    className="glass-card glow-blue" style={{ padding: 24, textAlign: 'center' }}
                  >
                    <div style={{ fontSize: 32, marginBottom: 12 }}>{f.emoji}</div>
                    <h4 style={{ fontWeight: 700, fontSize: 15, marginBottom: 4 }}>{f.name}</h4>
                    <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>{f.desc}</p>
                  </motion.div>
                ))}
              </div>

            </div>
          </div>
        </section>

      </main>
      <Footer />
    </>
  );
}
